### ISSUE TITLE
Incorrect path for conventional-changelog

### ISSUE THREAD

**Issue by airtonix** [bumped/bumped-changelog#11]
https://github.com/bumped/bumped-changelog/blob/master/lib/index.coffee#L8

```
Error: spawn C:\Users\zenobius\Projects\Mine\angular-named-routes\node_modules\bumped-changelog\node_modules\.bin\conventional-changelog ENOENT
  at exports._errnoException (util.js:873:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
  at onErrorNT (internal/child_process.js:344:16)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickCallback (node.js:356:17)
```

Perhaps it should be : 

```
...
conventionalChangelog = 'node_modules/.bin/conventional-changelog-cli'
...
```

**Comment by Kikobeats** [comment]
Thanks for that. Can you convert into a PR?

**Comment by airtonix** [comment]
Sure thing,

But looking closely, it should be executing conventional-changelog in this modules `node_modules` or the projects `node_modules` ?

**Comment by airtonix** [comment]
Actually the fix is the use `cross-spawn` not nodes built-in spawn. PR incoming.

**Comment by Kikobeats** [comment]
uhmm, I don't understand why `cross-spawn` is the solution but yea, I wanna see the PR 😄
