### ISSUE TITLE
ENOENT errors on changelog generation

### ISSUE THREAD

**Issue by jannisg** [bumped/bumped-changelog#18]
I keep running into this error and need some help debugging this as I'm not sure how to track down the root cause.

The error is this (after running my `bumped release` command:

```
→ yarn release -- minor
yarn release v0.17.10
$ yarn run bumped release minor
yarn run v0.17.10
$ "/Users/jannis/Sites/git/myproject/node_modules/.bin/bumped" release minor

bumped Releases version 0.17.0.

post bumped Starting Generating CHANGELOG file
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/jannis/Sites/git/myproject/node_modules/bumped-changelog/node_modules/conventional-changelog-cli/cli.js ENOENT
  at exports._errnoException (util.js:1022:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
  at onErrorNT (internal/child_process.js:359:16)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

Most of the time the command just works, but sometimes it just errors out like this.

I realise this doesn't provide a whole lot of information but any ideas on how I can dig into this and figure out why this is happening would be appreciated.

I'm running this with:
```
→ yarn --version
0.17.10

→ node --version
v7.2.1
```

In case this helps, here is my `.bumpedrc` file:

```
files: [
    package.json
]

plugins:

    postrelease:

        'Generating CHANGELOG file':
            plugin: 'bumped-changelog'
            options:
                filename: 'CHANGELOG.md'
                preset: 'angular'

        'Committing new version':
            plugin: 'bumped-terminal'
            command: 'git add CHANGELOG.md package.json && git commit -m "Release $newVersion"'

        'Publishing tag to BitBucket':
            plugin: 'bumped-terminal'
            command: 'git tag $newVersion && git push && git push --tags'

        'Creating zip archive for release':
            plugin: 'bumped-terminal'
            command: 'yarn run build && yarn run gulp zip'
```

**Comment by Kikobeats** [comment]
I think that it's related with Yarn.

The current implementation use `changelog/cli.js` file, check this line:
https://github.com/bumped/bumped-changelog/blob/master/lib/index.coffee#L33

The file normally lives under `node_modules`, but using yarn the file is not under this path, need a smart way to localize the file.

Can you add console.log and debug the trace?

**Comment by jannisg** [comment]
Okay, I've debugged this down to the path being incorrect, which seems to have been an intended change in this commit: https://github.com/bumped/bumped-changelog/commit/d1420ae31faf74a1435b79c8b046e3d031e9d783

If I locally revert that commit, i.e. go back to the `node_modules/.bin/conventional-changelog` symlinked path everything works fine.

I don't have a ready-to-go windows machine to test on, can you explain what the issue on Windows was?

I'm wondering if we could utilise an explicit `bin` entry in the `bumped-changelog` `package.json` file like so:

```
{
  ...
  "bin": {
    "conventional-changelog-cli": "./node_modules/conventional-changelog-cli/cli.js"
  }
  ...
}
```

To create an explicit symlink in `node_modules/.bin/conventional-changelog-cli` that we can then use/rely on?

**Comment by Kikobeats** [comment]
I avoid the symlink because it doesn't work fine under windws, see here: https://github.com/bumped/bumped-changelog/issues/11.

so, I'm understand that you are using Linux?

This is a tedious problem for cross-platform packages, because symlink works different, depend of the OS filesystem implementation. 

Maybe we can make a workaround using `path`, or exists a specific module for that. 

Can you open a PR with your proposition? Then I could test in my MacOSX and move this ahead.

**Comment by jannisg** [comment]
I'm using Mac OS X myself and am having this issue.

What I cannot grasp from #11 and #12 is whether the files are there and just not resolving correctly or something else is going on, i.e. the symlink is not being created for instance.

If it's just a matter of resolving the symlink path, perhaps we could use:

```coffee
changelog = path.resolve './node_modules/conventional-changelog-cli/cli.js'
```

I'm not entirely sure what `plugin.path` is derived from so not sure if that has something to do with it but as I understand we basically just want to resolve a local (to the plugin folder) reference anyway so perhaps we can just pass a relative file reference into `path.resolve`?

I might have to look into setting up a dev VM with windows to try this out but unfortunately I won't have time to do that this weekend :/

**Comment by Kikobeats** [comment]
@jannisg yea I think that the problem is the symlink.

People recommend me use fs.realpath: https://nodejs.org/api/fs.html#fs_fs_realpath_path_options_callback

That give you the absolute path of a symlink. This is the think that I changed in the PR.

Try when you can, no problem 😄
